version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout

      - run:
          name: Install uv
          command: |
            curl -Ls https://astral.sh/uv/install.sh | sh
            echo 'export PATH="$HOME/.cargo/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

      - run:
          name: Install dependencies using uv
          command: uv pip install --system -r <(uv pip compile --extra dev pyproject.toml)

      - run:
          name: Run tests
          command: pytest tests/ -v

      - run:
          name: Build package
          command: |
            python -m build

      - persist_to_workspace:
          root: .
          paths:
            - dist

  publish:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Install twine
          command: |
            python -m pip install --upgrade twine
      - run:
          name: Upload to PyPI
          command: |
            twine upload dist/* -u $PYPI_USERNAME -p $PYPI_PASSWORD

workflows:
  build-test-publish:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: main
